name: base
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - Pillow = 10.2.*
  - imagehash = 4.3.*
  - opencv = 4.9.*
  - uvicorn = 0.28.*
  - gunicorn = 21.2.*
  - dash = 2.16.*
  - dash-mantine-components = 0.12.*
  - dash-daq = 0.5.*
  - pip
  - streamlit = 1.33.*
  - wand = 0.6.*
  - halo = 0.0.31
  - scikit-image = 0.22.0
  - imageio = 2.34.*
  - fastapi = 0.111.*
  - uvicorn = 0.28.1
  - python-multipart = 0.0.9
  - pip:
    - dash-ace == 0.2.*
    - dash-bootstrap-components == 1.5.*
    - dash-cytoscape == 1.0.*
